# Generated by Django 5.0.4 on 2024-04-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_tile_collection_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
